### ISSUE TITLE
pmix failures with test playbook

### ISSUE THREAD

**Issue by verdurin** [NVIDIA/deepops#942]
```
[centos@admin00 deepops]$ ansible-playbook -l slurm-cluster playbooks/slurm-cluster/slurm-validation.yml -e '{num_gpus: 1}'

PLAY [slurm-master[0]] *****************************************************************************************************************************************************************************************************************************************************

TASK [Get node count from sinfo] *******************************************************************************************************************************************************************************************************************************************
changed: [login01]

TASK [Set num_nodes variable] **********************************************************************************************************************************************************************************************************************************************
ok: [login01]

TASK [Set cmd variable] ****************************************************************************************************************************************************************************************************************************************************
ok: [login01]

TASK [Print node/gpu counts] ***********************************************************************************************************************************************************************************************************************************************
ok: [login01] =>
  msg:
  - Detected 1 nodes with 1 gpus each.
  - 'Proceeding to run validation test, this may take several minutes: srun -N 1 -G 1 --ntasks-per-node=1 --mpi=pmix --exclusive  --container-image=deepops/nccl-tests-tf20.06-ubuntu18.04:latest all_reduce_perf -b 1M -e 4G -f 2 -g 1.'

TASK [Execute NCCL test across all nodes and GPUs] *************************************************************************************************************************************************************************************************************************
fatal: [login01]: FAILED! => changed=true
  cmd: |-
    srun -N 1 -G 1 --ntasks-per-node=1 --mpi=pmix --exclusive  --container-image=deepops/nccl-tests-tf20.06-ubuntu18.04:latest all_reduce_perf -b 1M -e 4G -f 2 -g 1
  delta: '0:01:08.614741'
  end: '2021-04-28 14:22:53.863193'
  msg: non-zero return code
  rc: 2
  start: '2021-04-28 14:21:45.248452'
  stderr: |-
    pyxis: importing docker image ...
    pyxis: creating container filesystem ...
    pyxis: starting container ...
    slurmstepd: error: gpu01 [0] pmixp_client_v2.c:211 [_errhandler] mpi/pmix: ERROR: Error handler invoked: status = -25, source = [slurm.pmix.3.0:0]
    srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
    srun: error: gpu01: task 0: Exited with exit code 2
  stderr_lines: <omitted>
  stdout: |-
    # nThread 1 nGpus 1 minBytes 1048576 maxBytes 4294967296 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
    #
    # Using devices
    gpu01: Test CUDA failure common.cu:732 'unknown error'
  stdout_lines: <omitted>

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************
login01                    : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by zyndagj** [comment]
Giving this issue a **verbose** bump.

### Summary
1. [slurm-validation.yml](https://github.com/NVIDIA/deepops/blob/5d3fd0655b1838ecfc8ac6bc5115d6b3d41cedcc/playbooks/slurm-cluster/slurm-validation.yml) playbook fails
2. Rebuilding with the most recent TF2 NGC container fails
3. Rebuilding with a TF2 container that matches system UCX fails
4. Running the rebuilt container with matching UCX version and `--mpi=pmi2` works
5. Running the rebuilt container with most recent TF2 and `--mpi=pmi2` does **not** work
6. Which MPI containers should work with DGX/DeepOps?

<hr>

I recently installed DeepOps on a 4-node DGX A100 POD. The install went smoothly, but the validation playbook would not run successfully.

```
login01:~/deepops$ ansible-playbook -l slurm-cluster playbooks/slurm-cluster/slurm-validation.yml -e '{num_gpus: 1}'
[WARNING]: error in 'jsonfile' cache, configured path (/var/tmp/ansible_cache) does not have necessary permissions (rwx), disabling
plugin

PLAY [slurm-master[0]] ******************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [login01]

TASK [Get node count from sinfo] ********************************************************************************************************
changed: [login01]

TASK [Set num_nodes variable] ***********************************************************************************************************
ok: [login01]

TASK [Set cmd variable] *****************************************************************************************************************
ok: [login01]

TASK [Print node/gpu counts] ************************************************************************************************************
ok: [login01] => 
  msg:
  - Detected 4 nodes with 1 gpus each.
  - 'Proceeding to run validation test, this may take several minutes: srun -N 4 -G 4 --ntasks-per-node=1 --mpi=pmix --exclusive  --container-image=deepops/nccl-tests-tf20.06-ubuntu18.04:latest all_reduce_perf -b 1M -e 4G -f 2 -g 1.'
TASK [Execute NCCL test across all nodes and GPUs] **************************************************************************************
fatal: [login01]: FAILED! => changed=true 
  cmd: |-
    srun -N 4 -G 4 --ntasks-per-node=1 --mpi=pmix --exclusive  --container-image=deepops/nccl-tests-tf20.06-ubuntu18.04:latest all_reduce_perf -b 1M -e 4G -f 2 -g 1
  delta: '0:01:13.461241'
  end: '2021-08-31 20:07:23.495566'
  msg: non-zero return code
  rc: 16
  start: '2021-08-31 20:06:10.034325'
  stderr: |-
    pyxis: importing docker image ...
    pyxis: importing docker image ...
    pyxis: importing docker image ...
    pyxis: importing docker image ...
    [gpu03:3926001] pml_ucx.c:119 Error: Failed to receive UCX worker address: Not found (-13)
    [gpu03:3926001] pml_ucx.c:386 Error: Failed to resolve UCX endpoint for rank 3
    [gpu01:3949673] pml_ucx.c:119 Error: Failed to receive UCX worker address: Not found (-13)
    [gpu01:3949673] pml_ucx.c:386 Error: Failed to resolve UCX endpoint for rank 1
    [gpu03:3926001] *** An error occurred in MPI_Allgather
    [gpu03:3926001] *** reported by process [1722433953,2]
    [gpu03:3926001] *** on communicator MPI_COMM_WORLD
    [gpu03:3926001] *** MPI_ERR_OTHER: known error not in list
    [gpu03:3926001] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
    [gpu03:3926001] ***    and potentially your MPI job)
    [gpu04:4043572] pml_ucx.c:119 Error: Failed to receive UCX worker address: Not found (-13)
    [gpu04:4043572] pml_ucx.c:386 Error: Failed to resolve UCX endpoint for rank 2
    [gpu01:3949673] *** An error occurred in MPI_Allgather
    [gpu01:3949673] *** reported by process [1722433953,0]
    [gpu01:3949673] *** on communicator MPI_COMM_WORLD
    [gpu01:3949673] *** MPI_ERR_OTHER: known error not in list
    [gpu01:3949673] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
    [gpu01:3949673] ***    and potentially your MPI job)
    [gpu04:4043572] *** An error occurred in MPI_Allgather
    [gpu04:4043572] *** reported by process [1722433953,3]
    [gpu04:4043572] *** on communicator MPI_COMM_WORLD
    [gpu04:4043572] *** MPI_ERR_OTHER: known error not in list
    [gpu04:4043572] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
    [gpu04:4043572] ***    and potentially your MPI job)
    [gpu02:3338259] pml_ucx.c:119 Error: Failed to receive UCX worker address: Not found (-13)
    [gpu02:3338259] pml_ucx.c:386 Error: Failed to resolve UCX endpoint for rank 0
    [gpu02:3338259] *** An error occurred in MPI_Allgather
    [gpu02:3338259] *** reported by process [1722433953,1]
    [gpu02:3338259] *** on communicator MPI_COMM_WORLD
    [gpu02:3338259] *** MPI_ERR_OTHER: known error not in list
    [gpu02:3338259] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
    [gpu02:3338259] ***    and potentially your MPI job)
    srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
    slurmstepd: error: *** STEP 41.0 ON gpu01 CANCELLED AT 2021-08-31T20:08:40 ***
    slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu04 [3]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.41.0:3]
    slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu03 [2]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.41.0:2]
    slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu02 [1]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.41.0:1]
    slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu01 [0]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.41.0:0]
    srun: error: gpu02: task 1: Exited with exit code 16
    srun: error: gpu03: task 2: Exited with exit code 16
    srun: error: gpu04: task 3: Exited with exit code 16
    srun: error: gpu01: task 0: Exited with exit code 16
  stderr_lines: <omitted>
  stdout: |-
    [1630440517.259485] [gpu04:4043572:0]          ib_md.c:1948 UCX  ERROR ibv_query_device(mlx5_0) returned 95: Operation not supported
    [1630440517.260526] [gpu04:4043572:0]          ib_md.c:1948 UCX  ERROR ibv_query_device(mlx5_1) returned 95: Operation not supported
...
    [1630440474.051528] [gpu02:3338259:0]          ib_md.c:1948 UCX  ERROR ibv_query_device(mlx5_11) returned 95: Operation not supported
    [1630440520.164633] [gpu01:3949673:0]          ib_md.c:1948 UCX  ERROR ibv_query_device(mlx5_11) returned 95: Operation not supported
  stdout_lines: <omitted>

PLAY RECAP ******************************************************************************************************************************
login01                    : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

we confirmed that IPoIB was correctly configured by making sure an IPv4 address was assigned to each adapter at the fabric level

<details><summary><b>login01:~$ for H in gpu0{1..4}; do sudo ssh $H bash -c 'hostname; ip a | grep ibp; echo'; done
</b></summary>

```
gpu01
7: ibp12s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.10.10/24 brd 100.200.10.255 scope global ibp12s0
8: ibp18s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.20.10/24 brd 100.200.20.255 scope global ibp18s0                                                                        
9: ibp75s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.40.10/24 brd 100.200.40.255 scope global ibp75s0                                                                        
10: ibp84s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.50.10/24 brd 100.200.50.255 scope global ibp84s0                                                                        
11: ibp141s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.60.10/24 brd 100.200.60.255 scope global ibp141s0                                                                       
12: ibp148s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.70.10/24 brd 100.200.70.255 scope global ibp148s0                                                                       
13: ibp186s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.80.10/24 brd 100.200.80.255 scope global ibp186s0                                                                       
14: ibp204s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.90.10/24 brd 100.200.90.255 scope global ibp204s0                                                                       
15: ibp225s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.30.10/24 brd 100.200.30.255 scope global ibp225s0f0                             

gpu02
7: ibp12s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.10.20/24 brd 100.200.10.255 scope global ibp12s0                                                                        
8: ibp18s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.20.20/24 brd 100.200.20.255 scope global ibp18s0
9: ibp75s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.40.20/24 brd 100.200.40.255 scope global ibp75s0
10: ibp84s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.50.20/24 brd 100.200.50.255 scope global ibp84s0
11: ibp141s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.60.20/24 brd 100.200.60.255 scope global ibp141s0
12: ibp148s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.70.20/24 brd 100.200.70.255 scope global ibp148s0
13: ibp186s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.80.20/24 brd 100.200.80.255 scope global ibp186s0
14: ibp204s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.90.20/24 brd 100.200.90.255 scope global ibp204s0
15: ibp225s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.30.20/24 brd 100.200.30.255 scope global ibp225s0f0 

gpu03
7: ibp12s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.10.30/24 brd 100.200.10.255 scope global ibp12s0
8: ibp18s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.20.30/24 brd 100.200.20.255 scope global ibp18s0
9: ibp75s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.40.30/24 brd 100.200.40.255 scope global ibp75s0
10: ibp84s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.50.30/24 brd 100.200.50.255 scope global ibp84s0
11: ibp141s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.60.30/24 brd 100.200.60.255 scope global ibp141s0
12: ibp148s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.70.30/24 brd 100.200.70.255 scope global ibp148s0
13: ibp186s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.80.30/24 brd 100.200.80.255 scope global ibp186s0
14: ibp204s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.90.30/24 brd 100.200.90.255 scope global ibp204s0
15: ibp225s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.30.30/24 brd 100.200.30.255 scope global ibp225s0f0

gpu04
6: ibp12s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.10.40/24 brd 100.200.10.255 scope global ibp12s0
7: ibp18s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.20.40/24 brd 100.200.20.255 scope global ibp18s0
8: ibp75s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.40.40/24 brd 100.200.40.255 scope global ibp75s0
9: ibp84s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.50.40/24 brd 100.200.50.255 scope global ibp84s0
10: ibp97s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.100.40/24 brd 100.200.100.255 scope global ibp97s0f0
11: ibp141s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.60.40/24 brd 100.200.60.255 scope global ibp141s0
12: ibp148s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.70.40/24 brd 100.200.70.255 scope global ibp148s0
13: ibp186s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.80.40/24 brd 100.200.80.255 scope global ibp186s0
14: ibp204s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.90.40/24 brd 100.200.90.255 scope global ibp204s0
15: ibp225s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    inet 100.200.30.40/24 brd 100.200.30.255 scope global ibp225s0f0
```

</details>

and confirmed that communication could take place between two nodes over IB

<details><summary><b>gpu01:~# ib_send_bw -d mlx5_1 -D 10 --report_gbits</b></summary>

```
************************************
* Waiting for client to connect... *
************************************
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF          Device         : mlx5_1
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 PCIe relax order: ON
 ibv_wr* API     : ON
 RX depth        : 512
 CQ Moderation   : 1
 Mtu             : 4096[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x57 QPN 0x0035 PSN 0x3d94ca
 remote address: LID 0x100 QPN 0x0067 PSN 0x9b50bf
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[Gb/sec]    BW average[Gb/sec]   MsgRate[Mpps]
Conflicting CPU frequency values detected: 3392.227000 != 2361.102000. CPU Frequency is not max.
 65536      2203880          0.00               192.58             0.367314
---------------------------------------------------------------------------------------
```

</details>
<details><summary><b>gpu02:~# ib_send_bw -d mlx5_0 -D 10 --report_gbits 100.200.20.10</b></summary>

```
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF          Device         : mlx5_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 PCIe relax order: ON
 ibv_wr* API     : ON
 TX depth        : 128
 CQ Moderation   : 1
 Mtu             : 4096[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x100 QPN 0x0067 PSN 0x9b50bf
 remote address: LID 0x57 QPN 0x0035 PSN 0x3d94ca
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[Gb/sec]    BW average[Gb/sec]   MsgRate[Mpps]
Conflicting CPU frequency values detected: 3396.452000 != 1828.428000. CPU Frequency is not max.
 65536      2203856          0.00               192.58             0.367312
---------------------------------------------------------------------------------------
```

</details>

Since the `deepops/nccl-tests-tf20.06-ubuntu18.04:latest all_reduce_perf` container was over a year old at this point, we rebuilt it with the [latest TF2 image on NGC](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow) using the following Dockerfile.

<details><summary><b>nccl-tests-tf21.08-ubuntu20.04.dockerfile</b></summary>

```
FROM nvcr.io/nvidia/tensorflow:21.08-tf2-py3 as nccl_tests
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        wget \
    && rm -rf /var/lib/apt/lists/*
ENV NCCL_TESTS_COMMITISH=bd0755c95c
WORKDIR /root/nccl_tests
RUN wget -q -O - https://github.com/NVIDIA/nccl-tests/archive/${NCCL_TESTS_COMMITISH}.tar.gz | tar --strip-components=1 -xzf - \
    && make MPI=1 MPI_HOME=/usr/local/mpi

FROM nvcr.io/nvidia/tensorflow:21.08-tf2-py3
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        openssh-client \
    && rm -rf /var/lib/apt/lists/*
COPY --from=nccl_tests /root/nccl_tests/build/* /usr/local/bin/
RUN ldconfig
```

</details>

and ran via `srun` after pushing to NGC, which also produced (different) UCX errors

<details><summary><b>login01:~$ srun -N 2 -G 2 --mpi=pmix --container-image=nvcr.io/nvidian/sae/nccl-tests-tf21.08-ubuntu20.04:latest all_reduce_perf -b 64 -e 1G -f 2 -g 1</b></summary>

```
pyxis: importing docker image ...
pyxis: importing docker image ...
[1630454524.011836] [gpu02:3552682:0]          wireup.c:1027 UCX  ERROR   old: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630454524.011891] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   old: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630454524.011896] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   old: lane[1]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] rkey_ptr
[1630454524.011899] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   old: lane[2]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630454524.011902] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   old: lane[3]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630454524.011906] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   old: lane[4]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[1630454524.011909] [gpu02:3552682:0]          wireup.c:1027 UCX  ERROR   new: am_lane 0 wireup_msg_lane 2 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630454524.011912] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   new: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630454524.011915] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   new: lane[1]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630454524.011918] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   new: lane[2]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630454524.011921] [gpu02:3552682:0]          wireup.c:1048 UCX  ERROR   new: lane[3]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[gpu02:3552682:0:3552682]      wireup.c:1336 Fatal: endpoint reconfiguration not supported yet
==== backtrace (tid:3552682) ====
 0  /opt/hpcx/ucx/lib/libucs.so.0(ucs_handle_error+0x2a4) [0x7f7b64db7824]
 1  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_message+0xb8) [0x7f7b64db4458]
 2  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d) [0x7f7b64db457d]
 3  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9) [0x7f7b64e5f5f9]
 4  /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0) [0x7f7b64e5d4c0]
 5  /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9) [0x7f7b64e5dcf9]
 6  /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69) [0x7f7b64d651d9]
 7  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9) [0x7f7b64e5c749]
 8  /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62) [0x7f7b64e5ca62]
 9  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e) [0x7f7b64e5f7be]
10  /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed) [0x7f7b64e0a7ed]
11  /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8) [0x7f7b64e0aa08]
12  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943) [0x7f7b64e8f943]
13  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48) [0x7f7b64e8fb38]
14  /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a) [0x7f7b72a6039a]
15  /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73) [0x7f7b72a131b3]
16  /usr/local/bin/all_reduce_perf(+0x3cef) [0x55dcf3b1dcef]
17  /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f7b67e640b3]
18  /usr/local/bin/all_reduce_perf(+0x473e) [0x55dcf3b1e73e]
=================================
[gpu02:3552682] *** Process received signal ***
[gpu02:3552682] Signal: Aborted (6)
[gpu02:3552682] Signal code:  (-6)
[gpu02:3552682] [ 0] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f7b682263c0]
[gpu02:3552682] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f7b67e8318b]
[gpu02:3552682] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f7b67e62859]
[gpu02:3552682] [ 3] /opt/hpcx/ucx/lib/libucs.so.0(+0x2845d)[0x7f7b64db445d]
[gpu02:3552682] [ 4] /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d)[0x7f7b64db457d]
[gpu02:3552682] [ 5] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9)[0x7f7b64e5f5f9]
[gpu02:3552682] [ 6] /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0)[0x7f7b64e5d4c0]
[gpu02:3552682] [ 7] /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9)[0x7f7b64e5dcf9]
[gpu02:3552682] [ 8] /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69)[0x7f7b64d651d9]
[gpu02:3552682] [ 9] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9)[0x7f7b64e5c749]
[gpu02:3552682] [10] /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62)[0x7f7b64e5ca62]
[gpu02:3552682] [11] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e)[0x7f7b64e5f7be]
[gpu02:3552682] [12] /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed)[0x7f7b64e0a7ed]
[gpu02:3552682] [13] /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8)[0x7f7b64e0aa08]
[gpu02:3552682] [14] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943)[0x7f7b64e8f943]
[gpu02:3552682] [15] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48)[0x7f7b64e8fb38]
[gpu02:3552682] [16] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a)[0x7f7b72a6039a]
[gpu02:3552682] [17] /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73)[0x7f7b72a131b3]
[gpu02:3552682] [18] /usr/local/bin/all_reduce_perf(+0x3cef)[0x55dcf3b1dcef]
[gpu02:3552682] [19] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f7b67e640b3]
[gpu02:3552682] [20] /usr/local/bin/all_reduce_perf(+0x473e)[0x55dcf3b1e73e]
[gpu02:3552682] *** End of error message ***
[1630454577.325630] [gpu01:193313:0]          wireup.c:1027 UCX  ERROR   old: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630454577.325679] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   old: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630454577.325684] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   old: lane[1]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] rkey_ptr
[1630454577.325687] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   old: lane[2]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630454577.325690] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   old: lane[3]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630454577.325693] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   old: lane[4]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[1630454577.325696] [gpu01:193313:0]          wireup.c:1027 UCX  ERROR   new: am_lane 0 wireup_msg_lane 2 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630454577.325699] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   new: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630454577.325701] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   new: lane[1]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630454577.325705] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   new: lane[2]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630454577.325707] [gpu01:193313:0]          wireup.c:1048 UCX  ERROR   new: lane[3]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[gpu01:193313:0:193313]      wireup.c:1336 Fatal: endpoint reconfiguration not supported yet
==== backtrace (tid: 193313) ====
 0  /opt/hpcx/ucx/lib/libucs.so.0(ucs_handle_error+0x2a4) [0x7f38c0042824]
 1  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_message+0xb8) [0x7f38c003f458]
 2  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d) [0x7f38c003f57d]
 3  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9) [0x7f38ba7775f9]
 4  /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0) [0x7f38ba7754c0]
 5  /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9) [0x7f38ba775cf9]
 6  /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69) [0x7f38ba6de1d9]
 7  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9) [0x7f38ba774749]
 8  /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62) [0x7f38ba774a62]
 9  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e) [0x7f38ba7777be]
10  /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed) [0x7f38ba7227ed]
11  /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8) [0x7f38ba722a08]
12  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943) [0x7f38c00fd943]
13  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48) [0x7f38c00fdb38]
14  /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a) [0x7f38cc3ae39a]
15  /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73) [0x7f38cc3611b3]
16  /usr/local/bin/all_reduce_perf(+0x3cef) [0x55a389235cef]
17  /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f38c17b20b3]
18  /usr/local/bin/all_reduce_perf(+0x473e) [0x55a38923673e]
=================================
[gpu01:193313] *** Process received signal ***
[gpu01:193313] Signal: Aborted (6)
[gpu01:193313] Signal code:  (-6)
[gpu01:193313] [ 0] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f38c1b743c0]
[gpu01:193313] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f38c17d118b]
[gpu01:193313] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f38c17b0859]
[gpu01:193313] [ 3] /opt/hpcx/ucx/lib/libucs.so.0(+0x2845d)[0x7f38c003f45d]
[gpu01:193313] [ 4] /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d)[0x7f38c003f57d]
[gpu01:193313] [ 5] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9)[0x7f38ba7775f9]
[gpu01:193313] [ 6] /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0)[0x7f38ba7754c0]
[gpu01:193313] [ 7] /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9)[0x7f38ba775cf9]
[gpu01:193313] [ 8] /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69)[0x7f38ba6de1d9]
[gpu01:193313] [ 9] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9)[0x7f38ba774749]
[gpu01:193313] [10] /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62)[0x7f38ba774a62]
[gpu01:193313] [11] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e)[0x7f38ba7777be]
[gpu01:193313] [12] /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed)[0x7f38ba7227ed]
[gpu01:193313] [13] /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8)[0x7f38ba722a08]
[gpu01:193313] [14] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943)[0x7f38c00fd943]
[gpu01:193313] [15] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48)[0x7f38c00fdb38]
[gpu01:193313] [16] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a)[0x7f38cc3ae39a]
[gpu01:193313] [17] /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73)[0x7f38cc3611b3]
[gpu01:193313] [18] /usr/local/bin/all_reduce_perf(+0x3cef)[0x55a389235cef]
[gpu01:193313] [19] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f38c17b20b3]
[gpu01:193313] [20] /usr/local/bin/all_reduce_perf(+0x473e)[0x55a38923673e]
[gpu01:193313] *** End of error message ***
slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu02 [1]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.60.0:1]
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu01 [0]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.60.0:0]
srun: error: gpu01: task 0: Aborted (core dumped)
srun: error: gpu02: task 1: Aborted (core dumped)
```

</details>

At this point I started querying UCX versions to see if that was the issue.

```
############################
# System UCX
############################
login01:~$ sudo ssh gpu01 ucx_info -v
# UCT version=1.9.0 revision 1d0a420
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/usr --enable-examples

############################
# Container UCX Versions
############################
login01:~$ for C in nvcr.io/nvidia/tensorflow:21.0{3..8}-tf2-py3; do echo "$C"; docker run --rm -it $C ucx_info -v | grep "^#"; done

nvcr.io/nvidia/tensorflow:21.03-tf2-py3
# UCT version=1.9.0 revision cd9efd3
# configured with: --prefix=/usr/local/ucx --enable-mt

nvcr.io/nvidia/tensorflow:21.04-tf2-py3
# UCT version=1.10.0 revision 0000000
# configured with: --prefix=/usr/local/ucx --enable-shared --disable-static --disable-doxygen-doc --enable-mt --disable-logging --disable-debug --disable-assertions --disable-params-check --without-knem --enable-cma --without-xpmem --without-java --enable-devel-headers --without-cuda --with-gdrcopy

nvcr.io/nvidia/tensorflow:21.05-tf2-py3
# UCT version=1.10.0 revision 0000000
# configured with: --prefix=/usr/local/ucx --enable-shared --disable-static --disable-doxygen-doc --enable-mt --disable-logging --disable-debug --disable-assertions --disable-params-check --without-knem --enable-cma --without-xpmem --without-java --enable-devel-headers --without-cuda --with-gdrcopy

nvcr.io/nvidia/tensorflow:21.06-tf2-py3
# UCT version=1.10.1 revision 0000000
# configured with: --prefix=/usr/local/ucx --enable-shared --disable-static --disable-doxygen-doc --enable-mt --disable-logging --disable-debug --disable-assertions --disable-params-check --without-knem --enable-cma --without-xpmem --without-java --enable-devel-headers --with-cuda=/usr/local/cuda --with-gdrcopy

nvcr.io/nvidia/tensorflow:21.07-tf2-py3
# UCT version=1.10.1 revision 0000000
# configured with: --prefix=/usr/local/ucx --enable-shared --disable-static --disable-doxygen-doc --enable-mt --disable-logging --disable-debug --disable-assertions --disable-params-check --without-knem --enable-cma --without-xpmem --without-java --enable-devel-headers --with-cuda=/usr/local/cuda --with-gdrcopy

nvcr.io/nvidia/tensorflow:21.08-tf2-py3
# UCT version=1.11.0 revision 6031c98
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --enable-mt --without-knem --with-xpmem=/hpc/local/oss/xpmem/90a95a4 --without-java --enable-devel-headers --with-cuda=/hpc/local/oss/cuda11.2 --with-gdrcopy --prefix=/build-result/hpcx-v2.9.0-gcc-inbox-ubuntu20.04-x86_64/ucx/mt
```

Since both the system and [nvcr.io/nvidia/tensorflow:21.03-tf2-py3](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow) used UCX 1.9.0, I created a new nccl test container using the following Dockerfile:

<details><summary><b>nccl-tests-tf21.03-ubuntu20.04.dockerfile</b></summary>

```
FROM nvcr.io/nvidia/tensorflow:21.03-tf2-py3 as nccl_tests
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        wget \
    && rm -rf /var/lib/apt/lists/*
ENV NCCL_TESTS_COMMITISH=bd0755c95c
WORKDIR /root/nccl_tests
RUN wget -q -O - https://github.com/NVIDIA/nccl-tests/archive/${NCCL_TESTS_COMMITISH}.tar.gz | tar --strip-components=1 -xzf - \
    && make MPI=1 MPI_HOME=/usr/local/mpi

FROM nvcr.io/nvidia/tensorflow:21.03-tf2-py3
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        openssh-client \
    && rm -rf /var/lib/apt/lists/*
COPY --from=nccl_tests /root/nccl_tests/build/* /usr/local/bin/
RUN ldconfig
```

</details>

and ran again.

<details><summary><b>login01:~$ srun -N 2 -G 2 --mpi=pmix --container-image=nvcr.io/nvidian/sae/nccl-tests-tf21.03-ubuntu20.04:latest all_reduce_perf -b 64 -e 1G -f 2 -g 1</b></summary>

```
pyxis: importing docker image ...
pyxis: importing docker image ...
[1630465253.944284] [gpu01:364061:0]    ucp_context.c:1077 UCX  ERROR exceeded transports/devices limit (66 requested, up to 64 are supported)

[1630465334.384573] [gpu02:3713251:0]    ucp_context.c:1077 UCX  ERROR exceeded transports/devices limit (66 requested, up to 64 are supported)
[gpu02:3713251] *** An error occurred in MPI_Allgather
[gpu02:3713251] *** reported by process [1774540670,1]
[gpu02:3713251] *** on communicator MPI_COMM_WORLD
[gpu02:3713251] *** MPI_ERR_INTERN: internal error
[gpu02:3713251] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[gpu02:3713251] ***    and potentially your MPI job)
[gpu01:364061] *** An error occurred in MPI_Allgather
[gpu01:364061] *** reported by process [1774540670,0]
[gpu01:364061] *** on communicator MPI_COMM_WORLD
[gpu01:364061] *** MPI_ERR_INTERN: internal error
[gpu01:364061] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[gpu01:364061] ***    and potentially your MPI job)
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 63.0 ON gpu01 CANCELLED AT 2021-09-01T03:03:07 ***
slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu01 [0]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.63.0:0]
slurmstepd: error:  mpi/pmix_v3: _errhandler: gpu02 [1]: pmixp_client_v2.c:210: Error handler invoked: status = -25, source = [slurm.pmix.63.0:1]
srun: error: gpu01: task 0: Exited with exit code 17
srun: error: gpu02: task 1: Exited with exit code 17
```

</details>

Which still failed. For fun, I tried launching with different `--mpi=` options, and `--mpi=pmi2` magically worked.


<details><summary><b>login01:~$ srun -N 2 -G 2 --mpi=pmi2 --container-image=nvcr.io/nvidian/sae/nccl-tests-tf21.03-ubuntu20.04:latest all_reduce_perf -b 64 -e 1G -f 2 -g 1</b></summary>

```
pyxis: importing docker image ...
pyxis: importing docker image ...
[1630465612.431007] [gpu01:370703:0]    ucp_context.c:1077 UCX  ERROR exceeded transports/devices limit (66 requested, up to 64 are supported)
[1630465561.342870] [gpu02:3719736:0]    ucp_context.c:1077 UCX  ERROR exceeded transports/devices limit (66 requested, up to 64 are supported)
# nThread 1 nGpus 1 minBytes 64 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid 370703 on      gpu01 device  0 [0x07] A100-SXM-80GB
#   Rank  1 Pid 3719736 on      gpu02 device  0 [0x07] A100-SXM-80GB
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
          64            16   float     sum    17.74    0.00    0.00  0e+00    17.18    0.00    0.00  0e+00
         128            32   float     sum    17.52    0.01    0.01  0e+00    17.47    0.01    0.01  0e+00
         256            64   float     sum    17.66    0.01    0.01  0e+00    17.55    0.01    0.01  0e+00
         512           128   float     sum    18.41    0.03    0.03  0e+00    17.97    0.03    0.03  0e+00
        1024           256   float     sum    19.15    0.05    0.05  0e+00    18.19    0.06    0.06  0e+00
        2048           512   float     sum    19.25    0.11    0.11  0e+00    18.84    0.11    0.11  0e+00
        4096          1024   float     sum    20.17    0.20    0.20  0e+00    20.04    0.20    0.20  0e+00
        8192          2048   float     sum    21.74    0.38    0.38  0e+00    21.94    0.37    0.37  0e+00
       16384          4096   float     sum    27.14    0.60    0.60  0e+00    27.01    0.61    0.61  0e+00
       32768          8192   float     sum    31.59    1.04    1.04  0e+00    30.85    1.06    1.06  0e+00
       65536         16384   float     sum    38.05    1.72    1.72  0e+00    34.28    1.91    1.91  0e+00
      131072         32768   float     sum    45.31    2.89    2.89  0e+00    44.79    2.93    2.93  0e+00
      262144         65536   float     sum    54.53    4.81    4.81  0e+00    52.97    4.95    4.95  0e+00
      524288        131072   float     sum    71.84    7.30    7.30  0e+00    68.96    7.60    7.60  0e+00
     1048576        262144   float     sum    108.2    9.69    9.69  0e+00    109.0    9.62    9.62  0e+00
     2097152        524288   float     sum    156.4   13.41   13.41  0e+00    155.1   13.52   13.52  0e+00
     4194304       1048576   float     sum    255.5   16.42   16.42  0e+00    253.9   16.52   16.52  0e+00
     8388608       2097152   float     sum    449.6   18.66   18.66  0e+00    451.0   18.60   18.60  0e+00
    16777216       4194304   float     sum    881.1   19.04   19.04  0e+00    875.5   19.16   19.16  0e+00
    33554432       8388608   float     sum   1751.3   19.16   19.16  0e+00   1730.5   19.39   19.39  0e+00
    67108864      16777216   float     sum   3463.0   19.38   19.38  0e+00   3452.8   19.44   19.44  0e+00
   134217728      33554432   float     sum   7576.1   17.72   17.72  0e+00   6900.2   19.45   19.45  0e+00
   268435456      67108864   float     sum    13754   19.52   19.52  0e+00    13723   19.56   19.56  0e+00
   536870912     134217728   float     sum    27620   19.44   19.44  0e+00    27465   19.55   19.55  0e+00
  1073741824     268435456   float     sum    54870   19.57   19.57  0e+00    54843   19.58   19.58  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 8.50772 
#
```

</details>

I just have no idea why. Running the 21.08 container with `--mpi=pmi2` also failed, so it seems like a combination of matching UCX versions and pmi2 are required.

<details><summary><b>login01:~$ srun -N 2 -G 2 --mpi=pmi2 --container-image=nvcr.io/nvidian/sae/nccl-tests-tf21.08-ubuntu20.04:latest all_reduce_perf -b 64 -e 1G -f 2 -g 1</b></summary>

```
pyxis: importing docker image ...
pyxis: importing docker image ...
[1630466014.672369] [gpu01:377932:0]          wireup.c:1027 UCX  ERROR   old: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630466014.672421] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   old: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630466014.672426] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   old: lane[1]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] rkey_ptr
[1630466014.672429] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   old: lane[2]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630466014.672432] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   old: lane[3]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630466014.672435] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   old: lane[4]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[1630466014.672438] [gpu01:377932:0]          wireup.c:1027 UCX  ERROR   new: am_lane 0 wireup_msg_lane 2 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630466014.672442] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   new: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630466014.672445] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   new: lane[1]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630466014.672448] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   new: lane[2]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630466014.672451] [gpu01:377932:0]          wireup.c:1048 UCX  ERROR   new: lane[3]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[gpu01:377932:0:377932]      wireup.c:1336 Fatal: endpoint reconfiguration not supported yet
==== backtrace (tid: 377932) ====
 0  /opt/hpcx/ucx/lib/libucs.so.0(ucs_handle_error+0x2a4) [0x7f976c195824]
 1  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_message+0xb8) [0x7f976c192458]
 2  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d) [0x7f976c19257d]
 3  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9) [0x7f976c23d5f9]
 4  /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0) [0x7f976c23b4c0]
 5  /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9) [0x7f976c23bcf9]
 6  /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69) [0x7f976c1431d9]
 7  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9) [0x7f976c23a749]
 8  /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62) [0x7f976c23aa62]
 9  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e) [0x7f976c23d7be]
10  /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed) [0x7f976c1e87ed]
11  /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8) [0x7f976c1e8a08]
12  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943) [0x7f976db53943]
13  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48) [0x7f976db53b38]
14  /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a) [0x7f977942539a]
15  /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73) [0x7f97793d81b3]
16  /usr/local/bin/all_reduce_perf(+0x3cef) [0x559e55265cef]
17  /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f976e8290b3]
18  /usr/local/bin/all_reduce_perf(+0x473e) [0x559e5526673e]
=================================
[gpu01:377932] *** Process received signal ***
[gpu01:377932] Signal: Aborted (6)
[gpu01:377932] Signal code:  (-6)
[gpu01:377932] [ 0] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f976ebeb3c0]
[gpu01:377932] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f976e84818b]
[gpu01:377932] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f976e827859]
[gpu01:377932] [ 3] /opt/hpcx/ucx/lib/libucs.so.0(+0x2845d)[0x7f976c19245d]
[gpu01:377932] [ 4] /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d)[0x7f976c19257d]
[gpu01:377932] [ 5] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9)[0x7f976c23d5f9]
[gpu01:377932] [ 6] /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0)[0x7f976c23b4c0]
[gpu01:377932] [ 7] /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9)[0x7f976c23bcf9]
[gpu01:377932] [ 8] /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69)[0x7f976c1431d9]
[gpu01:377932] [ 9] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9)[0x7f976c23a749]
[gpu01:377932] [10] /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62)[0x7f976c23aa62]
[gpu01:377932] [11] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e)[0x7f976c23d7be]
[gpu01:377932] [12] /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed)[0x7f976c1e87ed]
[gpu01:377932] [13] /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8)[0x7f976c1e8a08]
[gpu01:377932] [14] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943)[0x7f976db53943]
[gpu01:377932] [15] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48)[0x7f976db53b38]
[gpu01:377932] [16] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a)[0x7f977942539a]
[gpu01:377932] [17] /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73)[0x7f97793d81b3]
[gpu01:377932] [18] /usr/local/bin/all_reduce_perf(+0x3cef)[0x559e55265cef]
[gpu01:377932] [19] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f976e8290b3]
[gpu01:377932] [20] /usr/local/bin/all_reduce_perf(+0x473e)[0x559e5526673e]
[gpu01:377932] *** End of error message ***
[1630465961.361021] [gpu02:3726394:0]          wireup.c:1027 UCX  ERROR   old: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630465961.361074] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   old: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630465961.361079] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   old: lane[1]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] rkey_ptr
[1630465961.361082] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   old: lane[2]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630465961.361085] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   old: lane[3]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630465961.361088] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   old: lane[4]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[1630465961.361091] [gpu02:3726394:0]          wireup.c:1027 UCX  ERROR   new: am_lane 0 wireup_msg_lane 2 cm_lane <none> reachable_mds 0x1ffdf ep_check_map 0x0
[1630465961.361094] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   new: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630465961.361097] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   new: lane[1]: 18:rc_mlx5/mlx5_0:1.0 md[6]      -> md[6]/ib/sysdev[0] rma_bw#0
[1630465961.361101] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   new: lane[2]: 23:rc_mlx5/mlx5_1:1.0 md[7]      -> md[7]/ib/sysdev[1] rma_bw#1 wireup
[1630465961.361104] [gpu02:3726394:0]          wireup.c:1048 UCX  ERROR   new: lane[3]: 15:cuda_copy/cuda.0 md[4]        -> md[4]/cuda_cpy/sysdev[255] rma_bw#2
[gpu02:3726394:0:3726394]      wireup.c:1336 Fatal: endpoint reconfiguration not supported yet
==== backtrace (tid:3726394) ====
 0  /opt/hpcx/ucx/lib/libucs.so.0(ucs_handle_error+0x2a4) [0x7f285d6e6824]
 1  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_message+0xb8) [0x7f285d6e3458]
 2  /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d) [0x7f285d6e357d]
 3  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9) [0x7f285d78e5f9]
 4  /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0) [0x7f285d78c4c0]
 5  /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9) [0x7f285d78ccf9]
 6  /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69) [0x7f285d69c1d9]
 7  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9) [0x7f285d78b749]
 8  /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62) [0x7f285d78ba62]
 9  /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e) [0x7f285d78e7be]
10  /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed) [0x7f285d7397ed]
11  /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8) [0x7f285d739a08]
12  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943) [0x7f285f0e8943]
13  /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48) [0x7f285f0e8b38]
14  /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a) [0x7f286a9db39a]
15  /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73) [0x7f286a98e1b3]
16  /usr/local/bin/all_reduce_perf(+0x3cef) [0x555c23126cef]
17  /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f285fddf0b3]
18  /usr/local/bin/all_reduce_perf(+0x473e) [0x555c2312773e]
=================================
[gpu02:3726394] *** Process received signal ***
[gpu02:3726394] Signal: Aborted (6)
[gpu02:3726394] Signal code:  (-6)
[gpu02:3726394] [ 0] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f28601a13c0]
[gpu02:3726394] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f285fdfe18b]
[gpu02:3726394] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f285fddd859]
[gpu02:3726394] [ 3] /opt/hpcx/ucx/lib/libucs.so.0(+0x2845d)[0x7f285d6e345d]
[gpu02:3726394] [ 4] /opt/hpcx/ucx/lib/libucs.so.0(ucs_fatal_error_format+0x11d)[0x7f285d6e357d]
[gpu02:3726394] [ 5] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_init_lanes+0x3c9)[0x7f285d78e5f9]
[gpu02:3726394] [ 6] /opt/hpcx/ucx/lib/libucp.so.0(+0x784c0)[0x7f285d78c4c0]
[gpu02:3726394] [ 7] /opt/hpcx/ucx/lib/libucp.so.0(+0x78cf9)[0x7f285d78ccf9]
[gpu02:3726394] [ 8] /opt/hpcx/ucx/lib/libuct.so.0(uct_self_ep_am_bcopy+0x69)[0x7f285d69c1d9]
[gpu02:3726394] [ 9] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_msg_progress+0xc9)[0x7f285d78b749]
[gpu02:3726394] [10] /opt/hpcx/ucx/lib/libucp.so.0(+0x77a62)[0x7f285d78ba62]
[gpu02:3726394] [11] /opt/hpcx/ucx/lib/libucp.so.0(ucp_wireup_send_request+0x14e)[0x7f285d78e7be]
[gpu02:3726394] [12] /opt/hpcx/ucx/lib/libucp.so.0(+0x257ed)[0x7f285d7397ed]
[gpu02:3726394] [13] /opt/hpcx/ucx/lib/libucp.so.0(ucp_ep_create+0xe8)[0x7f285d739a08]
[gpu02:3726394] [14] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(+0x4943)[0x7f285f0e8943]
[gpu02:3726394] [15] /opt/hpcx/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_add_procs+0x48)[0x7f285f0e8b38]
[gpu02:3726394] [16] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_init+0x94a)[0x7f286a9db39a]
[gpu02:3726394] [17] /opt/hpcx/ompi/lib/libmpi.so.40(MPI_Init+0x73)[0x7f286a98e1b3]
[gpu02:3726394] [18] /usr/local/bin/all_reduce_perf(+0x3cef)[0x555c23126cef]
[gpu02:3726394] [19] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f285fddf0b3]
[gpu02:3726394] [20] /usr/local/bin/all_reduce_perf(+0x473e)[0x555c2312773e]
[gpu02:3726394] *** End of error message ***
srun: error: gpu02: task 1: Aborted (core dumped)
srun: error: gpu01: task 0: Aborted (core dumped)
```

</details>

This makes me wonder which systems these tensorflow containers are supposed support. This DGX A100 POD is running

<details><summary><b>gpu01:~# cat /etc/dgx-release</b></summary>

```
DGX_NAME="DGX Server"
DGX_PRETTY_NAME="NVIDIA DGX Server"
DGX_SWBUILD_DATE="2021-02-04-09-33-25"
DGX_SWBUILD_VERSION="5.0.2"
DGX_COMMIT_ID="bcf2581"
DGX_PLATFORM="DGX Server for DGX A100"
DGX_SERIAL_NUMBER="1574220001049"

DGX_OTA_VERSION="5.0.5"
DGX_OTA_DATE="Fri 13 Aug 2021 07:24:20 PM PDT"
```

</details>

and was provisioned with the latest version of DeepOps, yet they seem to be incompatible. Is there a way to identify which containers on NGC are compatible with the DGX ecosystem?

**Comment by dennisorlando** [comment]
I encountered the same exact error with a completely different task, which is not related in any way to NVIDIA/deepops. 
When trying to isolate the issue, I randomly got an "out of memory" error followed by the `mpi/pmix: ERROR: Error handler invoked: status = -25,` message.
I increased the memory available to the SLURM job and it fixed the problem. I decreased the memory available to the SLURM job and I correctly reproduced the same error. Interestingly, when decreasing the memory limit, I never got any "out of memory" error.
I think I was lucky to get it the first time.
